### ISSUE TITLE
12/10 Things to decide

### ISSUE THREAD

**Issue by seewhyjay** [AY2324S1-CS2103T-T12-3/tp#40]
# For `Assignment` model
1. [x] Abstract out `start` and `end` into their own classes to do validation -> abstract out as `date`, then check that `end` is not before `start`
2. [x] Fields -> completedness, end date (no start date), plan to finish by date (optional), description (optional)
3. [x] Exceptions -> DuplicateAssignmentException, AssignmentNotFound

# For logic
1. [x] Split commands into `assignment`, `events` and `internships`? Or common command for all -> Split
2. [x] Same for parser, split? Or common -> Split

# GUI
1. [x] How do we show the different views?
    - [x] Command that switches view (i.e `show-assignments` will show all assignments, then similar commands for the other 2)
    - [ ] Be able to show all 3 at once side-by-side
    - [ ] Something else
2. [x] Calendar view (priority.Low)
# Storage
1. [x] Save in a seperate json file for `assignments`, `events`, `internship` or all in one json file? -> one single save file
